import { useEffect, useState } from 'react'
import { api } from '../api/client'

export default function Outputs() {
  const [files, setFiles] = useState([])
  const [loading, setLoading] = useState(true)
  const [filter, setFilter] = useState('all')

  const load = () => {
    setLoading(true)
    api.outputs().then(d => { setFiles(d.files || []); setLoading(false) })
  }
  useEffect(load, [])

  const filtered = files.filter(f => {
    if (filter === 'pdf')  return f.filename.endsWith('.pdf')
    if (filter === 'pptx') return f.filename.endsWith('.pptx')
    return true
  })

  const fmt = (ts) => new Date(ts * 1000).toLocaleString('en-IN', { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit' })

  return (
    <div>
      <div className="page-hdr">
        <h2>Generated Outputs</h2>
        <p>All investment documents generated by the Content Engine</p>
      </div>

      <div style={{ display: 'flex', gap: 10, marginBottom: 20, alignItems: 'center' }}>
        {['all', 'pdf', 'pptx'].map(f => (
          <button key={f} className={`btn ${filter === f ? 'primary' : 'secondary'}`}
            onClick={() => setFilter(f)} style={{ padding: '7px 16px' }}>
            {f.toUpperCase()}
          </button>
        ))}
        <button className="btn secondary" onClick={load} style={{ marginLeft: 'auto' }}>
          Refresh
        </button>
      </div>

      {loading ? (
        <div style={{ display: 'flex', alignItems: 'center', gap: 10, color: 'var(--muted)' }}>
          <div className="spinner"></div> Loading files...
        </div>
      ) : (
        <div className="card">
          {filtered.length === 0 ? (
            <div style={{ textAlign: 'center', padding: 40, color: 'var(--muted)' }}>
              <div style={{ fontSize: 36, marginBottom: 12 }}>📄</div>
              <div style={{ fontWeight: 600 }}>No outputs yet</div>
              <div style={{ fontSize: 13, marginTop: 6 }}>Go to Generate to create your first document</div>
            </div>
          ) : (
            <div className="table-wrap">
              <table>
                <thead><tr>
                  <th>File</th><th>Type</th><th>Size</th><th>Generated</th><th>Download</th>
                </tr></thead>
                <tbody>
                  {filtered.map(f => (
                    <tr key={f.filename}>
                      <td>
                        <div style={{ fontWeight: 500 }}>{f.filename.replace(/_pitchdeck|_teaser|_one_pager/, '')}</div>
                        <div style={{ fontSize: 11, color: 'var(--muted)', marginTop: 2 }}>{f.filename}</div>
                      </td>
                      <td>
                        {f.filename.endsWith('.pdf')  && <span className="badge blue">PDF</span>}
                        {f.filename.endsWith('.pptx') && <span className="badge green">PPTX</span>}
                        {f.filename.endsWith('.json') && <span className="badge gray">JSON</span>}
                      </td>
                      <td style={{ color: 'var(--muted)', fontSize: 13 }}>{f.size_kb} KB</td>
                      <td style={{ color: 'var(--muted)', fontSize: 13 }}>{fmt(f.modified)}</td>
                      <td>
                        <a href={api.downloadUrl(f.filename)} target="_blank" rel="noreferrer"
                          className="btn primary" style={{ padding: '5px 14px', fontSize: 12 }}>
                          ⬇ Download
                        </a>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      )}
    </div>
  )
}
